name: heuristic
on: workflow_dispatch
jobs:
  jax2tf_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.11'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          # modify 1 line
          sudo apt install -y adduser
          pip install uv==0.5.31
      - run: |
          pip install uv~=0.5.30
      - run: |
          uv pip install --system .[minimum-jaxlib] -r build/test-requirements.txt
          uv pip install --system --pre tensorflow==2.19.0
      - run: |
          echo "JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES"
          echo "JAX_ENABLE_X64=$JAX_ENABLE_X64"
          echo "JAX_ENABLE_CHECKS=$JAX_ENABLE_CHECKS"
          echo "JAX_SKIP_SLOW_TESTS=$JAX_SKIP_SLOW_TESTS"
          pytest -n auto --tb=short --maxfail=20 jax/experimental/jax2tf/tests/jax2tf_test.py
    env:
      COLUMNS: '254'
      ENABLE_RUNTIME_UPTIME_TELEMETRY: '1'
      JAX_ENABLE_CHECKS: 'true'
      JAX_ENABLE_X64: '0'
      JAX_NUM_GENERATED_CASES: '10'
      JAX_SKIP_SLOW_TESTS: 'true'
      LC_CTYPE: C.UTF-8
      LINES: '62'
      TERM: xterm
      TF_CPP_MIN_LOG_LEVEL: '1'
